apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage-claim-nfs
  namespace: backstage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 2G